---
title: "R functions used in the app"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{r_functions_used_in_app}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(wedding)
library(tidyverse)
```

# Information about the wedding day organization

## Construst a count/countdown between two moments

```{r}
get_count_countdown_moments(start_moment = "2009-10-14 04:00:00",
                            end_moment = "2021-10-02 15:00:00",
                            text = "between the moment they met and the wedding")
```

## Construct a map

```{r}
data_markers <- tibble(
  longitude = c(2.1203232115689707, 2.119756986412269, 2.120561059665001),
  latitude = c(48.80504860237253, 48.78022930537074, 48.85858486573977),
  name = c(
    "<b>Palace of Versailles</b><br/>Super great place to get married", 
    "<b>A random place to stay</b>", 
    "<b>A random place to stay</b>")
)

get_map_wedding(
  data_markers = data_markers,
  icon_markers = "home"
)
```

```{r}
data_markers <- tibble(
  longitude = c(2.1203232115689707, 2.119756986412269, 2.120561059665001),
  latitude = c(48.80504860237253, 48.78022930537074, 48.85858486573977),
  name = c(
    "<b>Palace of Versailles</b><br/>Super great place to get married", 
    "<b>A random place to stay</b>", 
    "<b>A random place to stay</b>")
)

get_map_wedding(
  data_markers = data_markers,
  icon_markers = "star",
  zoom = 10
)
```

## Add guests info in database

```{r}
info_to_add <- tibble(
  name = c("David", "Margot"),
  here_cocktail = rep("Yes", 2),
  here_diner = rep("Yes", 2),
  here_sunday = rep("Yes", 2),
  special_diet = c(NA_character_, "I am vegan"),
  menu_diner = rep("Adult", 2),
  time_confirmation = rep("2021-04-22 09:57:12 CEST", 2)
)
  
data_guests <- tibble(
  name = c("David", "Margot", "Pierre", "Marie"),
  type = c("Adult", "Adult", "Kid", "Teen"),
  table = c(1, 1, 2, 2),
  announcement = c("Yes", NA_character_, "Yes", NA_character_),
  here_cocktail = c(rep(NA_character_, 3), "No"),
  here_diner = c(rep(NA_character_, 3), "No"),
  here_sunday = c(rep(NA_character_, 3), "No"),
  special_diet = c(rep(NA_character_, 4)), 
  menu_diner = c(rep(NA_character_, 4)),
  time_confirmation = c(rep(NA_character_, 3), "2021-01-22 07:28:14 CEST")
)

add_info_guests_in_database(info_to_add = info_to_add, data_guests = data_guests)
```

# Information about the wedding preparation

## Rename columns of table of expenses

```{r}
data(data_expenses_example)
data_expenses_example %>% 
  rename_expenses_to_fr()
```

## Get the total expenses

```{r}
data(data_expenses_example)
data_expenses_example %>% 
  get_total_expenses()
```

## Plot expenses by paymaster

```{r}
data(data_expenses_example)
data_expenses_example %>% 
  plot_expenses_by_paymaster()
```

## Count confirmations

```{r}
data(data_guests_example)
count_confirmations(filter_confirmation = c("type == 'Teen'",
                                            "(here_cocktail == 'No' | here_diner == 'No' | here_sunday == 'No')"),
                    data_guests = data_guests_example)
```

## Seating plan

```{r}
data(data_guests_table_example)

data_guests_table_example %>% 
  plot_one_seating_plan(id_table = 1)

data_guests_table_example %>% 
  plot_all_seating_plans()
```


